server:
  port: 8181  # The Single Entry Point

spring:
  application:
    name: api-gateway

#  cloud:
#    gateway:
#      routes:
#        # Route 1: Product Service
#        - id: product-service
#          uri: lb://PRODUCT-SERVICE  # 'lb' = Load Balanced (Ask Eureka)
#          predicates:
#            - Path=/api/product/** # If URL matches this... send to Product Service
#
#        # Route 2: Order Service
#        - id: order-service
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/api/order/**
#
#        # Route 3: User Service
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/api/user/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


logging:
  level:
    org.springframework.cloud.gateway: DEBUG