server:
  port: 8081  # <--- CHANGED PORT!

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_service


resilience4j:
  circuitbreaker:
    instances:
      inventory: # <--- We name our circuit breaker "inventory"
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5           # Check the last 5 calls
        failureRateThreshold: 50       # If 50% fail, stop calling Product Service
        waitDurationInOpenState: 5s    # Wait 5 seconds before trying again